// v:12.5.7
var skimlinks_domain = 'wordpress.redirectingat.com';
var skimlinks_legacy_support = true;
var skimlinks_cookie_sync_optout = true;
var skimlinks_audience_optout = false;
var skimlinks_first_party_na = false;
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var skimlinks_replace_timeout = 300;
var skimlinks_legacy_click_handlers = false;
var skimlinks_affiliate_unknown_links = true;
var noskimproducts = true;
var skimwords_instant = true;
if (typeof noskimwords === "undefined") {
var noskimwords = true;
}
var noskoupon = true;
var skimlinks_pub_id = '725X1342';

(function(h){var Hc,Ic,va,aa;aa=function(){var a,b,c,d,e,f,i,m,g,h,l,k,t,w,n,p,o,q;if(aa)return aa;d=function(a){return((null!=a?a[0]:void 0)||2)*{minutes:60,hours:3600,days:86400}[(null!=a?a[1]:void 0)||"days"]};p=[{label:"lotame",url:"//bcp.crwdcntrl.net/5/c=7507/pv=y?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[2,"days"],priority:1,active:!0},{label:"blue_kai",url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"dfp",url:"//cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[1,"days"],priority:2,active:!0},{label:"mediamath",url:"//pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",resyncAfter:[1,"days"],priority:2,active:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",
resyncAfter:[1,"days"],priority:2,active:!0},{label:"magnetic",url:"//magnetic.t.domdex.com/sync/skimlinks",resyncAfter:[7,"days"],priority:2,active:!0},{label:"exelate",url:"//x.skimresources.com/?provider=exelate",resyncAfter:[1,"days"],priority:2,active:!0},{label:"exelate2",url:"//x.skimresources.com/?provider=exelate2",resyncAfter:[1,"days"],priority:2,active:!0},{label:"krux",url:"//x.skimresources.com/?provider=krux",resyncAfter:[1,"days"],priority:2,active:!0},{label:"tapad",url:"//x.skimresources.com/?provider=tapad",
resyncAfter:[3,"days"],priority:3,active:!0},{label:"skim",url:"//x.skimresources.com/?provider=skim",resyncAfter:[5,"days"],priority:3,active:!0}];m={};b=function(a,b){var c,d,e,f;if(a.filter)return null!=(c=a.filter)?"function"===typeof c.call?c.call(a,b):void 0:void 0;d=[];for(c=e=0,f=a.length;0<=f?e<f:e>f;c=0<=f?++e:--e)b(a[c])&&d.push(a[c]);return d};h=function(a){m.syncCheck=a[0];m.getCookieSyncInfo=a[1];m.getServerTime=a[2];return m};t=function(a,b,c){return Boolean(a.timestamp+d(b.resyncAfter)<=
c)};q=function(a){return m.getServerTime(function(b){var c;c=g(a,b);return setInterval(function(){if(c.length)return i(c.shift())},200)})};n=function(a,b){var c;c=Math.max(1,Number(a.priority))-1;null==b[c]&&(b[c]=[]);return b[c].push(a)};o=function(a){var b,c,d,e;for(c=a.length;c;)d=Math.floor(Math.random()*c--),b=c,e=a[b],a[b]=a[d],a[d]=e;return a};g=function(a,c){var d,e,f,i,m;d=b(p,function(b){var d;return!b.active?!1:(d=a[b.label])?t(d,b,c):!0});e=[];f=b(d,function(a){return 1===a.priority});
d=f.length?f:d;for(i=0,m=d.length;i<m;i++)f=d[i],n(f,e);f=[];for(i=0,m=e.length;i<m;i++)d=e[i],null!=d&&f.push.apply(f,o(d));return f};l=function(a){return q(w(a))};w=function(a){var b,c,d,e,f;d={};if(!a)return d;f=a.split("|");for(a=0,e=f.length;a<e;a++)b=f[a],b=b.split(":"),c=b[0],d[c]={label:c,timestamp:parseInt(b[1])};return d};k=function(a){a.width=0;a.height=0;return a.style.display="none"};e=function(a,b){var c;null==b&&(b=j);c=b.createElement("img");c.src=a;c.width=1;c.height=1;return c};
a=function(a,b){var c;null==b&&(b=j);null!=(c=b.getElementsByTagName("body")[0])&&c.appendChild(a);return a};c=null;f=function(){var b;c=b=c||a(j.createElement("iframe"));k(b);return b.contentDocument||b.contentWindow.document};i=function(b){var c;c=f();return a(e(b.url,c),c)};return{init:function(){h(arguments);if(m.syncCheck())return m.getCookieSyncInfo(l)},__private__:{day:86400,isTimeToSync:t,configToSeconds:d,parseSyncCookie:w,getSuitableProviders:g,setProviders:function(a){return p=a}}}}();
var X,Jc,Kc,ba,Lc,Mc,Ob,l,s,Pb,wa,Qb,Rb,Sb,Na,Oa,Nc,hb,Oc,Pc,Tb,Ub,j,o,Pa,ib,Vb,jb,x,p,y,Wb,S,ca,xa,da,kb,ya,ea,za,Aa,Qc,Xb,q,Ba,Qa,Yb,lb,fa,ga,Rc,Sc,g,Tc,Ca,Uc,Vc,mb,Y,Wc,Xc,Ra,ha,Zb,Yc,Zc,$c,ad,Sa,I,bd,nb,ia,$b,ob,Ta,ja,ka,la,ac,pb,Ua,cd,Va,dd,ed,Da,fd,Wa,bc,ma,cc,gd,r,hd,dc,id,qb,Xa,jd,Ya,kd,ec,Za,rb,ld,fc,sb,md,gc,hc,nd,tb,ic,K,jc,kc,lc,T,mc,ub,nc,vb,oc,pc,na,wb,qc,N,$a,xb,J,Z,Ea,yb,rc,ab,zb,Ab,Bb,Cb,Db,U,bb,Fa,Eb,E,Ga,A,B,oa,sc,L,od,Fb,pd,cb,qd,G,tc,uc,rd,Gb,vc,wc,V,v,u,Hb,xc,yc,Ha,pa,O,M,db,
qa,Ia,ra,C,D,zc,H,sd,z,td,P,Ac,F={}.hasOwnProperty,sa=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};da=kb=null;"undefined"!==typeof skimlinks_context_window&&null!==skimlinks_context_window&&(h=h[skimlinks_context_window]);j=h.document;ya=/http:/g;p=function(){return function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&
/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}}(this)();fa=[];ga=[];q={};Yb=(new Date).getTime();Ba=[];Qc=["buy.itunes.apple.com","itunes.apple.com","itunes.com"];lb={"t.umblr.com":{name:"z"}};ea=S=null;Qa=xa=!1;za=[];ca=[];Aa=[];y={domains:[]};x={};Wb=null;Xb=[];U=B=null;N="";Ga=E=bb=$a=null;na=[];Z=[];J=Eb=vb=wb=ab=null;Ea=!1;rc="beginning";yb=[];A=oa=!1;oc="skimlinksApplyHandlers";ub=Fa=!1;zb=300;pc=qc=Cb=Bb=Ab=Db=nc=!1;uc=[];ra=qa=Ia=db=C=null;
H=D=v="";M=u=0;Ha=yc=pa=wc=zc=!1;V=[];O=!0;xc=vc=!1;Hb=[];z=h.location;P="";X=!1;cb=null;Za={};Gb=[];ec=!1;ib=[];Hc=["noskim","norewrite"];Ic="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");xb=function(){return!0};va=[];Ca=function(a){var b;b=j.createElement("a");b.href=a;return L(b.hostname)};md=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};Rc=function(){var a,
b;a="";for(b=0;8>b;++b)a+=md();return a};g=function(){return function(a,b){return null!=h[a]?h[a]:null!=window[a]?window[a]:b}}(this);Lc=function(){var a;H=Rc();kb=null!=(a=j.getElementsByTagName("html"))?a[0]:void 0;za=g("skimlinks_included_classes",[]);ca=g("skimlinks_excluded_classes",[]);Aa=g("skimlinks_included_ids",[]);da=g("force_location")?Ca(g("force_location")):z.hostname;B=g("skimlinks_tracking",!1);B=g("affiliate_tracking",B);U=g("skimlinks_site")||g("skimlinks_sitename")||!1;N=g("skimlinks_domain")?
"http://"+g("skimlinks_domain"):"";$a=g("skimlinks_google",!1);bb=null!=$a?$a:"skimout";E=g("skimlinks_target",!1);Ga=g("sl_test",!1);g("skimlinks_cookie_sync",[]);na=g("skimlinks_exclude",[]);Z=g("skimlinks_include",[]);ab=g("skimlinks_noright",!1);wb=g("skimlinks_exrel",!1);vb=g("skimlinks_byrel",!1);Eb=g("skimlinks_blocked_tag",!1);oa=g("skimlinks_revenue_forecast",!1);Fa=g("skimlinks_strip_attribute",!1);ub=g("skimlinks_ad_images",!1);"number"===typeof g("skimlinks_replace_timeout")&&(zb=g("skimlinks_replace_timeout"));
"boolean"===typeof g("skimlinks_before_click_handler")&&(nc=g("skimlinks_before_click_handler"));J=0;A=Zc();Db=g("skimlinks_retargetting_trigger",!1);Ab=g("skimlinks_retargetting_adv_id",!1);Bb=g("skimlinks_retargetting_pix_id",!1);Cb=!1;qc=g("skimlinks_first_party_na",!1);"undefined"!==typeof skimlinks_cookie_sync_optout&&null!==skimlinks_cookie_sync_optout&&(pc=skimlinks_cookie_sync_optout);g("skimwords_live_scraping",!1);ec=g("skimlinks_url_extraction_rules",!1);ib=g("skimlinks_extra_redir_params",
[]).join("&");h.skimlinks_revenue_forecast=window.skimlinks_revenue_forecast=!1;C=g("skimlinks_pub_id","");Xb=g("skimlinks_link_impression_exclude_selector",[]).join(", ");if(g("skimlinks_legacy_support"))h.skimlinks=window.skimlinks=function(){return!0},g("mugicPopWin")&&(h._mugicPopWin=window._mugicPopWin=h.mugicPopWin),h.mugicPopWin=window.mugicPopWin=function(){return!0},h.mugicRight=window.mugicRight=function(){return!0},h.mugicRightClick=window.mugicRightClick=function(){return!0};u=g("skimlinks_dnt",
0);M=g("skimlinks_nocookie",!1);M=g("skimlinks_nocookie",!1);db=g("noimpressions",!1);qa=g("noskimlinks",!1)||g("noskim",!1)||!1;O=g("skimlinks_legacy_click_handlers",!0);vc=g("skimlinks_affiliate_unknown_links",!1);qa&&($.skimlinks=!1);(Ia=g("noskimwords",!1)||g("noskim",!1)||!1)&&($.skimwords=!1);ra=g("nounlinked",!1)||g("noskim",!1)||!1;uc=g("unlinked_excludes",[]);ra&&($.unlinked=!1);zc=g("skim_toolbar",!1);wc=g("skimlinks_ajax_rerun",!1);g("skimlinks_editor",!1);yc=g("skimlinks_ipc",!1);Ha=g("skimlinks_ipc_diy",
!1);xc=g("skimlinks_dwell_tracking",!1);Hb=g("skimlinks_dwell_allowed_urls",[]);g("_merchantSettings")&&"undefined"===typeof replace_url_field?(pa=!0,oc="skimlinksApplyHandlersAlt"):pa=!1;Ea=g("skimlinks_ipc_decoration",!1);rc=g("skimlinks_ipc_position","beginning");yb=g("skimlinks_ipc_domain_whitelist",[]);if(h.document&&h.document.referrer)P=h.document.referrer;fd(da)&&(Ia=qa=!0);B&&!/^[a-z0-9_\\|]+$/i.test(B)&&(B=!1);if("undefined"!==typeof n&&null!==n)n.pag=k.pag=g("force_location",z.href),n.pub=
k.pub=C,n.uc=k.uc=B;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();ca.push("noskimlinks");ca.push("noskim");cb=j.createTextNode("").nodeName;return!0};td=function(){return!pc};sd=function(a,b){return a.hasOwnProperty(b)};Zc=function(){var a;return"function"===typeof(a=new Date).getTimezoneOffset?a.getTimezoneOffset():void 0};fd=function(a){var b,c,d,e;if(c=g("noskim_domains",!1))for(d=0,e=c.length;d<e;d++)if(b=c[d],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0;
return!1};L=function(){return function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}}(this)();s=function(){return function(){return j.addEventListener?function(a,b,c,d){null==d&&(d=!1);if(a&&(a.nodeName||a===h))return a.addEventListener(b,c,d)}:function(a,b,c){if(a&&(a.nodeName||a===h))return a.attachEvent("on"+b,function(){return 7>p.version&&!h.event?(setTimeout(function(){return c.call(a,h.event)},100),!0):c.call(a,h.event)})}}}(this)();(function(){return function(){return j.createElement("div").getElementsByClassName?
function(a,b){return I(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=Sb(b);return Vb(a,c)}}})(this)();o=function(){return function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];return function(c){var d,e,c=encodeURIComponent(c);for(d=0,e=b.length;d<e;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}}(this)();Ua=function(){return function(){var a;
a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!da||-1===c.indexOf(da))&&(!da||-1===da.indexOf("."+c))}}}(this)();l=function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(e){return null}};Oa=function(a,b,c){arguments[1]="data-"+b;return l.apply(this,arguments)};pd=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?
a.innerText=b:a.textContent=b,c=b;return c};nb=function(a){return(""+a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};G=function(){return function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}}(this)();Jc=function(a,b){return!I(a,b)?(a.className+=" "+
b,!0):!1};id=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)F.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=r(b):(b=r(b),e+='"'+f+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};r=function(){return function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):id}}(this)();
Pa=function(){return function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}}(this)();sb={topics:{},on:function(a,b){var c;if(null==(c=this.topics)[a])c[a]=[];return this.topics[a].push(b)},off:function(a,b){var c;c=0<=sa.call(this.topics[a],b);if(-1<c)return this.topics[a].splice(c,1)},once:function(a,b){var c;c=function(a){return function(){c.called||b.apply(a,arguments);return c.called=!0}}(this);c.called=!1;return this.on(a,c)},
publish:function(a,b){var c,d,e,f,i,m;c={topic:a,extra:b};if(this.topics[a]){i=this.topics[a];m=[];for(e=0,f=i.length;e<f;e++)d=i[e],m.push("function"===typeof d?d(c):void 0);return m}}};Sb=function(a){a=Pa(a);return RegExp("\\b"+a+"\\b","i")};I=function(a,b){return a.className?Sb(b).test(a.className):!1};Vb=function(a,b){var c,d,e,f,i;d=[];a.className&&b.test(a.className)&&d.push(a);i=a.childNodes;for(e=0,f=i.length;e<f;e++)c=i[e],d=d.concat(Vb(c,b));return d};Wa=function(a){for(var b,c,d,e;a&&a!==
kb;){c=a.id;for(d=0,e=za.length;d<e;d++)if(b=za[d],I(a,b))return!1;for(d=0,e=Aa.length;d<e;d++)if(b=Aa[d],c===b)return!1;for(c=0,d=ca.length;c<d;c++)if(b=ca[c],I(a,b))return!0;a=a.parentNode}return za.length||Aa.length?!0:!1};la=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+Pa(b)+")|(?:noskim))\\b","i");null!=a&&a!==kb;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};Qb=function(a,b){var c,d,e,f,i,m,h;C||(C=g("skimlinks_pub_id",""));m=P?"&pref="+o(P):"";c=
!1;0<b.indexOf("#slm-")&&(d=b.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1])===10*d[1]&&(b=d[0],c=d[1]));e=l(a,"data-skimlinks-editor")&&1===parseInt(l(a,"data-skimlinks-editor"))?1:0;N||(N=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na());I(a,"skimwords-link")?(h=l(a,"data-skimwords-word"),d=l(a,"data-skim-creative"),f=l(a,"data-skim-product"),i=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na(),"undefined"!==typeof settings&&null!==settings&&(i=settings.sw_domain||
i),b=""+i+"/?id="+C+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=2")+"&url="+o(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&isjs=1&xword="+(h?h:"")+"&xcreo="+(d?d:"")+"&xpid="+(f?f:"")+"&xed="+e+"&sref="+o(z)+""+m+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):I(a,"skimlinks-inline")?(d=l(a,"data-skim-creative"),b=""+N+"/?id="+C+""+(U?"&site="+U:"")+""+(Ga?"&test="+Ga:"")+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=8")+"&isjs=1&url="+o(b)+"&xguid="+
v+"&xuuid="+H+"&xsessid="+D+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+o(z)+"&pref="+o(P)+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:"")):la(a,"noskimlinks")||(d=l(a,"data-skim-creative"),b=""+N+"/?id="+C+""+(U?"&site="+U:"")+""+(Ga?"&test="+Ga:"")+""+(B?"&xcust="+B:"")+""+(!1!==c?"&xs=9":"&xs=1")+"&isjs=1&url="+o(b)+"&xguid="+v+"&xuuid="+H+"&xsessid="+D+"&xcreo="+(a&&null!=d?d:0)+"&xed="+e+"&sref="+o(z)+""+m+""+(u?"&dnt="+u:"")+""+(M?"&fdnt=1":"")+
""+(!1!==c?"&slmcid="+c:"")+""+(!1!==A?"&xtz="+A:""));0<ib.length&&(b+="&"+ib);X&&!la(a,"noskimlinks")&&(b+="&abp=1");return b};Sa=function(a){var b,c,d;if(ub)return!1;if(a.hasChildNodes()){d=a.childNodes;for(a=0,c=d.length;a<c;a++)if(b=d[a],b=Sa(b))return!0}else return Ta(a);return!1};Ta=function(a){var b,c,d,e,f;if(ub)return!1;b=[[300,250],[302,252],[304,254],[300,300],[302,302],[304,304],[468,60],[470,62],[472,64],[728,90],[730,92],[732,94]];if(a&&a.nodeName&&"IMG"===a.nodeName.toUpperCase()){d=
a.offsetWidth||0;c=a.offsetHeight||0;for(e=0,f=b.length;e<f;e++)if(a=b[e],d===a[0]&&c===a[1])return!0}return!1};mb=function(a){var b;b=a.target||a.srcElement;if(O&&b&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName.toUpperCase()&&"AREA"!==b.nodeName.toUpperCase();){if(Ta(b))return null;b=Ra(b)}return b};K=function(a){var b;b=mb(a);if(!b||Sa(b))return!0;hc(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=h.event,a.cancelBubble=!0);return!0};Ra=
function(a){for(;a.parentNode;){a=a.parentNode;if(Ta(a))break;if("A"===(null!=a?a.nodeName.toUpperCase():void 0)||"AREA"===(null!=a?a.nodeName.toUpperCase():void 0))return a}return null};od=function(a){return a=v?a.replace(/([&\?]{1})xguid=([a-fA-F0-9]{32})/,"$1xguid="+v):a.replace(/([&\?]{1}xguid=[a-fA-F0-9]{32})/,"")};Rb=function(a,b){var c,d;d=a();if(null!=d)return function(a){return a(d)};c=null;sb.once(b,function(){return"function"===typeof c?c(a()):void 0});return function(a){return c=a}};Uc=
function(){var a;return null!=(a=va[0])?a.guid:void 0};Tc=Rb(function(){var a;return null!=(a=va[0])?a.csp:void 0},"beacon");$c=Rb(function(){var a;return null!=(a=va[0])?a.ts:void 0},"beacon");hc=function(a){var b,c,d,e;d=!1;b=$a;a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a));if(a){e=Vc(a);N||(N=g("skimlinks_domain")?"http://"+g("skimlinks_domain"):Na());c=N;if(e.length>=c.length&&e.substr(0,c.length)===c)return!0;if("msie"===p.browser&&a.childNodes.length&&
3===a.childNodes[0].nodeType)d=a.innerHTML;c=-1!==e.indexOf(c)?e:Qb(a,e);b&&ud(e);ic(a);a.href=c;a.href=c;d&&a.innerHTML!==d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),zb)}return!0};Na=function(){var a;a="msie"===p.browser&&8>=p.version;return!Uc()&&!a?"//go.skimresources.com":"//go.redirectingat.com"};ma=function(a){return-1!==(N||Na()).indexOf(a)||-1!==a.indexOf("go.redirectingat.com")||-1!==a.indexOf("go.skimresources.com")};ac=function(a){return!0===x[a]||(null===x[a]||
void 0===x[a])&&vc&&!ma(a)};Da=function(a){return oa?(ac(a)&&(J+=1),!1):ac(a)};kd=function(a){return a in lb};cc=function(a){var b,c;if(!Eb)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+Eb+"]").toLowerCase();c=pd(b);if(!c)return!1;c=c.toLowerCase();c=G(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};ka=function(a){return!a||vb&&a===vb||!bd(a)};bd=function(a){var b,c,d,e;if(!a)return!1;b=a.toLowerCase().split(/\s+/);a=wb?[wb.toLowerCase()]:[];a=a.concat(Hc);for(d=0,e=
b.length;d<e;d++)if(c=b[d],0<=sa.call(a,c))return!0;return!1};Pb=function(){var a,b,c,d;S={};ea={};U&&na.push(U);d=na.concat(Ic);for(b=0,c=d.length;b<c;b++)a=d[b],S[a]=a.length;for(b=0,c=Z.length;b<c;b++)a=Z[b],ea[a]=a.length;return S};pb=function(a){var b,c,d;(null===S||null===ea)&&Pb();if(!a)return!1;for(b in S)if(F.call(S,b))if(c=S[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;return!1};cd=function(a){var b,c,d;(null===S||
null===ea)&&Pb();if(!a)return!1;if(0===Z.length)return!0;for(b in ea)if(F.call(ea,b))if(c="*"===b.substr(0,1),d="*"===b.substr(b.length-1,1),b=b.replace(/\*/g,""),c&&d){if(-1!==a.indexOf(b))return!0}else if(c){if(-1!==a.indexOf(b)&&a.indexOf(b)===a.length-b.length)return!0}else if(d){if(0===a.indexOf(b))return!0}else if(a===b)return!0;return!1};ja=function(a,b){return Ua(a,b)&&!pb(b)&&cd(b)};ed=function(a,b,c){return"selector_bl"===b?dd(a,c):!1};dd=function(a,b){return!a&&!b?!1:Boolean(b&&("function"===
typeof a.closest?a.closest(b):void 0))};tb=function(a){if(O&&10>a)return Ba=nd(),setTimeout(function(){return tb(a+1)},2E3*a)};nd=function(){var a,b,c,d,e,f,i;if(O){b={};d=[];c=[];for(e=0,f=Ba.length;e<f;e++)a=Ba[e],a.parentNode?c.push(a):b[a.href]=1;i=Y();for(e=0,f=i.length;e<f;e++)a=i[e],b[a.href]&&d.push(a);Ob(d,!1);return d.concat(c)}};Kc=function(a,b){var c,d,e;d=[];oa&&(a.xrf=1);for(c in a)F.call(a,c)&&(e=a[c],"data"!==c&&d.push(""+c+"="+e));a.data&&d.push("data="+a.data);return b+"?"+d.join("&")};
qd=function(a){var b,c;b=Ca(a);if(ma(b))return!0;b="";0<a.indexOf("#slm-")&&(c=a.split("#slm-"),2===c.length&&!isNaN(c[1])&&10*parseInt(c[1])===10*c[1]&&(a=c[0],b=c[1]));a={call:"track",data:o('{"pubcode":"'+C+'", "referrer":"'+z+'", "pref":"'+P+'", "site":"'+U+'", "url":"'+a+'", "custom":"'+B+'", "xtz":'+A+', "uuid":"'+H+'", "slmcid":"'+b+'", "product":"1"}')};u&&(a.dnt=u);M&&(a.fdnt=1);a=Kc(a,"//t.skimresources.com/api/");a=a+"&rnd="+Math.random();Wc(a);return!0};ic=function(a){var b,c;if(!(null!==
a&&a.sl_href_restore_scheduled))return b=a.href,c="msie"===p.browser&&7>p.version?1E4:zb,a.sl_href_restore_scheduled=!0,setTimeout(function(){return function(){a.href=b;a.href=b;return delete a.sl_href_restore_scheduled}}(this),c)};ad=function(a,b){var c,d;d=!1;c=od(b);if(c!==b&&(a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Ra(a)),a)){if("msie"===p.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;ic(a);a.href=c;a.href=c;d&&a.innerHTML!==
d&&setTimeout(function(){return function(){return a.innerHTML=d}}(this),300)}return c};jc=function(a,b){var c,d;sc(a);E&&l(a,"target",E);d=l(a,"onclick");c="click"===b.type||"contextmenu"===b.type;if(null!=d&&-1!==d.toString().indexOf("return false")){if(c)return xb(a),fc(b)}else return xb(a),K(b)};rb=function(a){var b,c,d;b=mb(a);d=b.href;c=Ca(d);ma(c)&&(d=ad(b,d));""===v&&qc?jc(b,a):qd(d);return!0};Wc=function(a){var b,c;b=j.getElementsByTagName("body")[0];c=j.createElement("img");c.src=a;c.width=
1;c.height=1;if("undefined"!==typeof c.style)c.style.display="none";b.appendChild(c);return c};ha=function(a,b,c,d,e){var t;var f,i,m,g,h;null==c&&(c={});f=c.charset||null;h=c.target||null;t=null!=(i=c.async)?i:!0,c=t;i=null!=h&&h.document?h.document:j;m=i.getElementsByTagName("head")[0];g=i.createElement("script");g.type="text/javascript";if(f)g.charset=f;if(b)g.onload=g.onreadystatechange=function(a){return function(){var c;c=!1;return function(){var d;d=a.readyState;if(!c&&(!d||"complete"===d||
"loaded"===d))return g.onload=g.onreadystatechange=null,c=!0,b.call(h),!0}}}(this)();g.onerror=function(){if(null!=d)return null!=e?d(e):d(!1)};g.async=!1!==c;g.src=a;m.appendChild(g);return g};Y=function(a,b){var c,d,e,f,i,m;e=null;a&&(e=RegExp("\\b"+Pa(a)+"\\b","i"));m=[];b||(b=j);d=b.getElementsByTagName("a");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&(!e||c.className&&e.test(c.className))&&m.push(c)}catch(g){}}d=b.getElementsByTagName("area");for(f=0,i=d.length;f<i;f++){c=d[f];try{c.href&&
(!e||c.className&&e.test(c.className))&&m.push(c)}catch(h){}}return m};Va=function(a){return-1!==a.indexOf("itunes.apple.com")||-1!==a.indexOf("itunes.com")||-1!==a.indexOf("phobos.apple.com")?!0:!1};sc=function(a){var b,c,d;if(!Fa)return!1;for(c in Fa)if(sd(Fa,c)&&(d=Fa[c],(b=l(a,c))&&0===b.indexOf(d)))b=b.substr(d.length),l(a,c,b);return!0};bc=function(a){return a&&Db&&!Cb&&ia(""+a,Db)};Ob=function(a,b){var c,d,e,f,i,m,g,h,j,k,t;null==b&&(b=!0);f=za.length||Aa.length||ca.length;m=[];d=0;for(k=0,
t=a.length;k<t;k++)if(c=a[k],i=L(c.hostname),c.sl_hidden_domain&&(i=L(c.sl_hidden_domain)),j=G(c.href),Ua(j,i)){h=l(c,"rel");g=l(c,"onclick");l(c,"sl-processed",1);c["sl-processed"]=1;e=Zb(j);bc(e)&&Ub(Ab,Bb);if(b&&ja(j,i)&&(Da(i)?(d++,q.hasOwnProperty(j)?q[j].ae=1:q[j]={count:0,ae:1}):q.hasOwnProperty(j)||(q[j]={count:0,ae:0}),q[j].count++,e))q[j].slmcid=e,0>sa.call(V,e)&&V.push(e);J=d;if(!pa||!Va(j))if((!f||!Wa(c))&&!cc(c))Da(i)||Va(j)?(q.hasOwnProperty(j)&&(q[j].ae=1),ka(h)&&(sc(c),E&&l(c,"target",
E),null!=g&&-1!==g.toString().indexOf("return false")?s(c,"click",fc):s(c,"click",K),Fb(c,!1),ob(c),m.push(c),ab||s(c,"contextmenu",K),xb(c))):Ua(j,i)&&!pb(i)&&ka(h)&&(E&&l(c,"target",E),s(c,"click",rb),ab||s(c,"contextmenu",rb))}return m};fc=function(a){var b;b=mb(a);if(g("_mugicPopWin"))return g("_mugicPopWin")(b);K(a);return(E?h.open(b.href):h.open(b.href,E)).focus()};ob=function(a,b){var c,d,e,f,i;if(g("link_icon")||0<a.getAttribute("data-skim-product")&&g("skimwords_product_icon")){if(0<a.getElementsByTagName("img").length)return!0;
if("msie"===p.browser&&8>p.version)a.style.display="inline-block";d=c="";null!=b&&(c=g("skimwords_icon_class",""),d=g("skimwords_icon_link_class",""));i=l(a,"title").replace("'","&#39;");e=g("link_icon")||g("skimwords_product_icon");f=j.createElement("a");l(f,"href",l(a,"href"));l(f,"title",i);l(f,"style","border:0px;padding:0;margin:0");l(f,"skimlinked","skimlinked");l(f,"target","_blank");I(a,"skimlinks-unlinked")||I(a,"skimwords-link")?(l(f,"data-skim-creative",Oa(a,"skim-creative")),l(f,"data-group-id",
Oa(a,"group-id")),l(f,"data-skimwords-word",Oa(a,"skimwords-word")),l(f,"data-skimwords-id",Oa(a,"skimwords-id")),I(a,"skimlinks-unlinked")?l(f,"class","skimlinks-icon-link "+d+" skimlinks-unlinked"):l(f,"class","skimlinks-icon-link "+d+" skimwords-link")):(l(f,"data-skim-creative",""),l(f,"data-group-id",""),l(f,"data-skimwords-word",""),l(f,"data-skimwords-id",""),l(f,"class","skimlinks-icon-link "+d));d=j.createElement("img");l(d,"src",e);l(d,"class",c);l(d,"skimlinked","skimlinked");l(d,"style",
"margin: 0px 0px -3px 2px !important; float:none !important; border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;");f.appendChild(d);c=j.createElement("div");c.appendChild=f;c=c.childNodes[0];s(c,"mousedown",K);a.appendChild(f)}return!0};Yc=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:h.getComputedStyle?j.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};ia=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],
c===a)return!0;return!1};lc=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),sb.publish("beacon",a));null!=h.skimlinks_runner&&(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],ma(b)||(x[b]=!0);for(b in x)null===x[b]&&(x[b]=!1);O&&(b=Y(),Ba=Ob(b),J+=Ba.length,!Qa&&"undefined"!==typeof ta&&null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains)),
mc());ra||Bc(a);return!0};Zb=function(a){return-1!==a.indexOf("#slm-")&&(a=a.split("#slm-"),2===a.length&&!isNaN(a[1])&&10*parseInt(a[1])===10*a[1])?parseInt(a[1]):null};Tb=function(a){var b,c,d,e,f,i,m,g;a||(a=0);if(h.skimlinks_requests_in_flight&&5>a)setTimeout(function(){return Tb(a+1)},400*a);else{e=Y();c=0;for(m=0,g=e.length;m<g;m++)if(b=e[m],i=G(b.href),d=L(b.hostname),f=l(b,"class"),(!f||!(-1!==f.indexOf("skimwords-link")||-1!==f.indexOf("skimlinks-unlinked")))&&ja(i,d)&&!ed(b,"selector_bl",
Xb))if(b=Zb(i),bc(b)&&Ub(Ab,Bb),Da(d)?(c++,q.hasOwnProperty(i)?q[i].ae=1:q[i]={count:0,ae:1}):q.hasOwnProperty(i)||(q[i]={count:0,ae:0}),q[i].count++,b)q[i].slmcid=b,0>sa.call(V,b)&&V.push(b);J=c;!Qa&&"undefined"!==typeof ta&&null!==ta&&null!=y&&null!=y.domains&&(Qa=!0,ta(y.domains));mc()}return!0};mc=function(){"undefined"!==typeof eb&&null!==eb&&(yc||Ha)&&x.length&&eb();"undefined"!==typeof Ja&&null!==Ja&&Ja("skimlinks");return!0};Ub=function(a,b){var c;if(!a||!b)return!1;Cb=!0;h.adroll_adv_id=
a;h.adroll_pix_id=b;h.__adroll_loaded=!0;c=j.createElement("script");c.setAttribute("async","true");c.type="text/javascript";c.src="//s.adroll.com/j/roundtrip.js";return j.getElementsByTagName("head").length?j.getElementsByTagName("head")[0].appendChild(c):j.getElementsByTagName("script")[0].parentNode.appendChild(c)};jb=function(){var a,b,c,d,e,f,i;d=Y();c=[];for(f=0,i=d.length;f<i;f++)a=d[f],b=L(a.hostname),e=G(a.href),a=l(a,"rel"),b&&ja(e,b)&&ka(a)&&!ma(b)&&void 0===x[b]&&(c.push(b),y.domains.push(b),
x[b]=null);return c};Mc=function(){var a;a=j.getElementsByTagName("body");if(0<a.length)return s(a[0],"click",ba),s(a[0],"contextmenu",ba)};ba=function(a){var b,c,d;if(h.event)a=h.event;c=a.originalTarget||a.srcElement||a.target;try{if("A"!==(null!=c?c.nodeName.toUpperCase():void 0)&&c.parentNode)c=Ra(c)}catch(e){c=null}if(!c||Sa(c)||Wa(c)||!ka(l(c,"rel")))return!0;try{b=l(c,"sl-processed")||0,null==c["sl-processed"]&&(b=0)}catch(f){b=0}if((d=l(c,"class"))&&(-1!==d.indexOf("skimwords-link")||-1!==
d.indexOf("skimlinks-inline")||-1!==d.indexOf("skimlinks-unlinked")))b=!0;if("A"===(null!=c?c.nodeName.toUpperCase():void 0)&&0===b)if(b=c,c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c&&ja(b.href,L(b.hostname))){hc(b);if(g("vglnk")&&I(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=h.event,a.cancelBubble=!0);return!0}};tc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return tc(a,b-1,c)}};Xc=function(a){if(null==
a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=tc(function(){return a.parentNode},3,null),null==a||Ta(a))return null;return a};Vc=function(a){var b,c;return ec&&(b=L(a.hostname),b in lb)?(b="[&?]"+lb[b].name+"=(http[^&]+)",decodeURIComponent(null!=(c=a.href)?c.match(RegExp(b)).pop():void 0)||a.href):a.href};gd=function(a){return!a||!a.href||0!==a.href.indexOf("http://")&&0!==a.href.indexOf("https://")&&0!==a.href.indexOf("//")?!1:!0};hb=function(a){var b,c,d,e;if(h.event)a=h.event;b=a.originalTarget||
a.srcElement||a.target;c=null!=b?b.nodeName.toUpperCase():void 0;"A"!==c&&"AREA"!==c&&(b=Xc(b));if(!b||Sa(b)||Wa(b)||!ka(l(b,"rel"))||cc(b))return!0;e=G(b.href);c=L(b.hostname);d="click"===a.type||"contextmenu"===a.type;if(gd(b)&&ja(b.href,c)){b.sl_hidden_domain&&(c=L(b.sl_hidden_domain));if(pa&&Va(e))return!0;if(Da(c)||Va(e)||kd(c))jc(b,a);else if(d&&Ua(e,c)&&!pb(c))return E&&l(b,"target",E),rb(a);return!0}};jd=function(a,b){var c,d,e,f,i,m;null==b&&(b=oc);h.skimlinks_requests_in_flight=(null!=(c=
h.skimlinks_requests_in_flight)?c:0)+1;if(!(null!=a&&a.length))return h[b](),!1;c=o('{"pubcode":"'+C+'","domains":_DOMAIN_LIST_,"page":"'+z.href+'"}');f="//r.skimresources.com/api/?callback="+b+(u?"&dnt="+u:"")+(M?"&fdnt=1":"")+(zc?"&call=toolbar":"")+"&data="+c;c="msie"===p.browser?2E3:8E3;e=[];for(i=0,m=a.length;i<m;i++)d=a[i],e.push(d),f.replace("_DOMAIN_LIST_",o(r(e))).length>c&&(e=e.slice(0,-1));f=f.replace("_DOMAIN_LIST_",o(r(e)));return ha(f,!1,{})};wa=function(a){var b,c;b=[];oa&&(a.xrf=1);
for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+o(a[c]));return b.join("&")};Xa=function(a,b,c){var d,e,f;if("msie"!==p.browser)e=!1,f=new XMLHttpRequest,f.open("POST",a,!0),f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=sa.call(f,"withCredentials")&&(f.withCredentials=!0),f.async="true",f.onreadystatechange=function(){var a,b;if(e)return!0;if(4===f.readyState){e=!0;if(200===f.status){a={};b=f.responseText;if(0===b.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&
null!==JSON&&JSON.parse)try{a=JSON.parse(f.responseText)}catch(d){}c(a);return!0}return!1}},f.send(b);else if(h.XDomainRequest){if(d=new XDomainRequest,0<=sa.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if(0===d.responseText.indexOf("//"))return c(a),!0;if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};d.ontimeout=
function(){return!1};d.async=!0;try{d.send(b)}catch(i){return!1}}}else return!1;return!0};Ya=function(a,b){var c;c={data:r({pubcode:C,domains:a,page:z.href})};wa(c);jd(a,b);return!0};qb=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],(null===x[b]||void 0===x[b])&&c.push(b);return c.length?Ya(c):!0};gc=function(){var a,b,c,d,e,f;c=Y();f=[];for(d=0,e=c.length;d<e;d++)(a=c[d])&&a.href?(b=Ca(a.href),0>sa.call(Qc,b)?(l(a,"sl-processed",0),f.push(a["sl-processed"]=0)):f.push(void 0)):f.push(void 0);
return f};$b=function(){return"undefined"!==typeof aa&&null!==aa?"function"===typeof aa.init?aa.init(td,Tc,$c):void 0:void 0};Ac=function(){if(h.skimlinksInitialized&&"function"!==typeof post_skimwords_hook)return!0;h.skimlinksInitialized=!0;dc();$b();pa&&gc();wc&&!qa&&Mc();qa||(jb(),ra&&Ya(y.domains));"undefined"!==typeof ua&&null!==ua&&!ra&&ua();"undefined"!==typeof skimwords&&null!==skimwords&&!Ia&&skimwords();return!0};hd=function(){if(xa)return!1;xa=!0;return Ac()};ld=function(a){var b,c;b=0;
for(c in a)F.call(a,c)&&(b+=1);return b};Fb=function(a,b){var c,d;d=a.style.cssText;""!==d&&(d+=" ");g("link_background")&&(c=g("link_background"),-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ");if(null!==g("link_tooltip",null))a.title=g("link_tooltip");if(b){g("skimwords_color")&&(c=g("skimwords_color"),-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ");g("skimwords_weight")&&(d+="font-weight: "+g("skimwords_weight")+" !important; ");g("skimwords_decoration")&&
(c=g("skimwords_decoration"),d="double"===c?d+"border-bottom: 1px double !important; ":"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; "));g("skimwords_style")&&(c=g("skimwords_style"),d+="font-style: "+c+" !important; ");g("skimwords_link_style")&&(c=g("skimwords_link_style"),d+=c+"; ");c=" "+a.className;if(g("skimwords_link_class"))c+=" "+g("skimwords_link_class"),a.className=c.substring(1);if(null!==g("skimwords_title",null))a.title=g("skimwords_title");
if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};T=function(){return O?hd():Pc()};Oc=function(){var a;h.skimlinksInitialized=!0;$b();pa&&gc();qa||(a=jb(),Ya(a),nc&&s(j,"mouseup",hb,!0),s(j,"click",hb,!0),s(j,"contextmenu",hb,!0));return dc()};rd=function(a,b){var c,d,e,f,i;e=!1;if(Hb){d=Sc(a);0===d.length&&(e=!0);for(f=0,i=d.length;f<
i;f++)if(c=d[f],0<=c.indexOf(b)){e=!0;break}}return e};Sc=function(a){var b,c,d,e;c=[];for(d=0,e=a.length;d<e;d++)b=a[d],b=b.replace(/https?\:\/\//,""),b=b.split("?")[0],c.push(b.split("#")[0]);return c};dc=function(){var a;a=rd(Hb,location.host+location.pathname);if(xc&&a&&"function"===typeof SkimPageIntelligence)return a="undefined"!==typeof Q&&null!==Q?Q:"//t.skimresources.com/api/",Wb=SkimPageIntelligence({dataCollectionUrl:a+"dwelltime",pub:C,guid:v,uuid:H,sessid:D}),Wb.start()};Pc=function(){if(xa)return!1;
xa=!0;return Ya(jb(),"skimlinksApplySecondaryHandlers")};kc=function(){return function(){return function(){var a,b,c;Lc();ce.detect(function(a){return X=a});if(g("skimlinks_revenue_forecast")&&g("skimlinks")||h.skimInitAlreadyCalled)return!1;O||Oc();b=function(){if(xa)return!0;try{j.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return T()};a=function(){return function(){return j.addEventListener?function(){j.removeEventListener("DOMContentLoaded",a,!1);T();return!0}:j.attachEvent?
function(){j.detachEvent("onreadystatechange",a);T();return!0}:function(){T();return!0}}}(this)();if("complete"===j.readyState)setTimeout(T,1);else if(j.addEventListener)j.addEventListener("DOMContentLoaded",a,!1),h.addEventListener("load",T,!1);else if(j.attachEvent){j.attachEvent("onreadystatechange",a);h.attachEvent("onload",T);c=!1;try{c=null===h.frameElement}catch(d){}j.documentElement.doScroll&&c&&b()}return h.skimInitAlreadyCalled=!0}}}(this)();Nc=function(a,b){return setTimeout(b,a)};h.skimlinksApplyHandlers=
lc;h.skimlinksApplySecondaryHandlers=function(a){var b,c,d,e;h.skimlinks_requests_in_flight-=1;a=null!=a?a:{};arguments.length&&(va.push(a),sb.publish("beacon",a));null!=h.skimlinks_runner&&(h.skimlinks_runner.skimlinks=1);a.guid&&""===v&&(v=a.guid);a.sessid&&""===D&&(D=a.sessid);e=a.merchant_domains||[];for(c=0,d=e.length;c<d;c++)b=e[c],ma(b)||(x[b]=!0);for(b in x)null===x[b]&&(x[b]=!1);"undefined"!==typeof ua&&null!==ua&&!ra&&ua();"undefined"!==typeof skimwords&&null!==skimwords&&!Ia&&skimwords();
return Tb()};h.skimlinksApplyHandlersAlt=lc;h.skimlinksAjaxHandlerByClass=function(a){var b,c,d;if(O&&"function"===typeof j.getElementsByClassName){b=j.getElementsByClassName(a);for(c=0,d=b.length;c<d;c++)a=b[c],s(a,"click",ba),s(a,"contextmenu",ba);return!0}return!1};h.skimlinksAjaxHandlerById=function(a){return O&&(a=j.getElementById(a))?(s(a,"click",ba),s(a,"contextmenu",ba),!0):!1};h.skimlinksRewriteUrl=Qb;h.skim_init=kc;!g("mugicPopWin")&&!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&
(h.mugicPopWin=K);!g("mugicRight")&&!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.mugicRight=K);h.skimlinksReload=function(){T();return!0};!g("skimlinks_legacy_support")&&!g("skimlinks_revenue_forecast")&&(h.skimlinks=Ac);var vd,wd,Ib,Cc,fb,xd,yd,zd,Ad,Bd,Dc,Jb,Cd,Dd,Ka,Ed,Fd,W,Ec,F={}.hasOwnProperty;Ec=W=0;fb=!1;Cc=function(a){var b;return a&&-1!==a.indexOf("class=")?(b=a.match(/([^\[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a:a};zd=function(a){Za[a]=Za[a]||0;Za[a]++;
return a+"_"+Za[a]};Ib=function(a){var b,c,d;b=c=null;-1!==a.indexOf(".")?(a=a.split("."),d=a[0],b=a[1]):-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],b=a[1].split("]"),b=b[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],c=a[1].split("]"),c=c[0]):d=a;return{tag:d,id:c,"class":b}};Jb=function(a,b){var c,d,e,f,i,g;e=b.split(",");for(i=0,g=e.length;i<g;i++){b=e[i];b=G(b);b=Ib(b);f=!0;c=a.className||("function"===
typeof a.getAttribute?a.getAttribute("class"):void 0)||"";d=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";if(b.tag&&(!a.nodeName||a.nodeName.toLowerCase()!==b.tag))f=!1;if(b["class"]&&(!c||c!==b["class"]&&0!==c.indexOf(b["class"])))f=!1;if(b.id&&(!d||d!==b.id&&-1===d.indexOf(b.id)))f=!1;if(f)return!0}return!1};yd=function(a){var b,c,d,e,f,i;if("undefined"!==typeof j.querySelectorAll)return j.querySelectorAll(a);e=[];a=Ib(a);if(a.tag&&a["class"]){d=j.getElementsByTagName(a.tag);
for(f=0,i=d.length;f<i;f++)b=d[f],(c=b.className||b.getAttribute("class"))&&0===c.indexOf(a["class"])&&e.push(b)}else a.tag&&a.id?(b=j.getElementById(a.id))&&b.nodeName.toLowerCase()===a.tag&&e.push(b):(a=a.tag,e=j.getElementsByTagName(a));return e};Ad=function(a,b,c){var d,e,f,i,g;d=[];if("undefined"!==typeof a.querySelectorAll)d=a.querySelectorAll(b);else if(b=Ib(b),b.tag&&b["class"]){if(!a.getElementsByTagName)return c?[]:!1;f=a.getElementsByTagName(b.tag);for(i=0,g=f.length;i<g;i++)if(a=f[i],
(e=a.className||a.getAttribute("class"))&&0===e.indexOf(b["class"]))if(c)d.push(a);else return!0}else if(b.tag&&b.id){if((a=j.getElementById(b.id))&&a.nodeName&&a.nodeName.toLowerCase()===b.tag)if(c)d.push(a);else return!0}else b=b.tag,d=a.getElementsByTagName(b);return c?d:0<d.length};Dc=function(a,b){return 0===b.length?!1:Jb(a,b.join(","))?!0:a.parentNode?Dc(a.parentNode,b):!1};Bd=function(a){var b;b=a.offsetWidth;a=a.offsetHeight;return 468===b&&60===a||234===b&&60===a||728===b&&90===a||300===
b&&250===a||250===b&&250===a||336===b&&280===a||160===b&&600===a||120===b&&600===a?!0:!1};xd=function(){var a;a=[];a.push("div.widget-content");a.push("div.googleAdText");a.push("div[id=ad]");a.push("div[id=banner]");a.push("div[id=advertisement]");a.push("div[id=adv_container]");a.push("div.ad");a.push("div.banner");a.push("div.advertisement");a.push("div.ad_container");a.push("span.IL_AD");a.push("div[id=fave-ext-container]");a.push("span.skimlinks-unlinked");-1!==z.href.indexOf(".google.")?(a.push("td.gac_c"),
a.push("table[id=mbEnd]"),a.push("div[id=mbEnd]"),a.push("span[id=taw]"),a.push("td.std"),a.push("div.std"),a.push("table.gssb_e"),a.push("div.c"),a.push("div[id=tads]")):-1!==z.href.indexOf(".yahoo.")?(a.push("ul.spns,ul.reducepx-spnslist"),a.push("ul[class*=reducepx-spnslist]"),a.push("ul[id=east]")):-1!==z.href.indexOf(".aol.")?(a.push("div.sllLink"),a.push("div.n")):-1!==z.href.indexOf(".bing.")&&(a.push("div.sb_adsW"),a.push("div[id=sidebar]"),a.push("div.sb_adsWv2"),a.push("div.sb_adsNv2"),
a.push("div[class*=sb_ads]"));return a};Dd=function(a){var b,c,d,e;c={};for(d=0,e=a.length;d<e;d++)b=a[d],c[b]=!0;return c};Ka=function(){var a;a={};return{traverse:function(b,c,d,e){b=b||[];c=c||[];d=d||[];return a&&a.length&&!e?a:this.traverse_dom(b,c,d)},traverse_dom:function(b,c,d){var e,f,i,g,h,j,l,k;if(fb)return a;fb=!0;f=this.get_exclude_selector(c);e=this.get_exclude_selector([]);c=f.selector;f=f.needed;e=e.selector;0===b.length&&b.push("body");b=b.concat(d);for(h=0,l=b.length;h<l;h++){i=
b[h];i=Cc(i);i=yd(i);for(g=j=0,k=i.length;j<k;g=++j)g=i[g],this.traverse_node(g,f,e,c,d)}return a},traverse_node:function(b,c,d,e,f){var i,g;g=[];i=0;for(g.push({node:b,tagName:"",readOnly:!1,parent_id:null});i<g.length;){if((b=g[i].node)&&!Bd(b)&&!la(b,"noskimwords",!0)&&(!c||!(""!==d&&Jb(b,d)))){g[i].readOnly=!1;if(b.nodeName&&b.nodeName!==cb){g[i].tagName=b.nodeName;if(null!==g[i].parent_id)g[i].readOnly=g[g[i].parent_id].readOnly;if(!g[i].readOnly)if(c&&Jb(b,e))g[i].readOnly=!0;else if(ia(b.nodeName.toLowerCase(),
f))g[i].readOnly=!0;if(ia(b.nodeName.toLowerCase(),f))g[i].readOnly=!0}else if(null!==g[i].parent_id)g[i].tagName=g[g[i].parent_id].tagName,g[i].readOnly=g[g[i].parent_id].readOnly;"msie"===p.browser&&9>p.version&&g[i].readOnly||(b.hasChildNodes()?g=this.add_child_nodes(g[i],i,g):this._add(b,!1,g[i].tagName,g[i].readOnly))}i++}return a},is_traversed:function(){return fb},is_good_tag:function(a){return Dd("p,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,section,main".split(","))[a.nodeName.toLowerCase()]?
!0:!1},is_html:function(a){return(a=G(a))&&"<"===a[0]},get_non_colliding_nodes:function(){var b,c,d;d=a;c={};Ec=0;for(b in d)F.call(d,b)&&(c[b]=d[b],Ec++);return c},get_as_hash_node_dict:function(){var b,c,d;c={};for(b in a)d=a[b],a.hasOwnProperty(b)&&(c[b]=d);return c},get_as_pair_array:function(){var b,c;c=[];for(b in a)F.call(a,b)&&c.push([b,a[b]]);return c},get_exclude_selector:function(a,c){var d,e,f,g,m,h;g=[];if(!c){c=j.getElementsByTagName("body");if(!c.length)return{needed:!1,selector:""};
c=c[0]}a=a.concat(xd());for(d=e=0,f=a.length;e<f;d=++e)a[d]=Cc(a[d]);e=!1;f="";for(m=0,h=a.length;m<h;m++)d=a[m],Ad(c,d,!1)&&g.push(d);g.length&&(e=!0,f=g.join(",").replace("class=","class^="));return{needed:e,selector:f}},length:function(){return ld(a)},reset:function(){a=[];return fb=!1},add_child_nodes:function(a,c,d){var e,f,g,m;m=a.node.childNodes;for(f=0,g=m.length;f<g;f++)(e=m[f])&&e.nodeName&&(this._add(e,!1,a.tagName,a.readOnly)||this.is_good_tag(e)&&d.push({node:e,tagName:a.tagName,readOnly:a.readOnly,
parent_id:c}));return d},add_node:function(a,c){return this._add(a,c)},_add:function(b,c,d,e){var f;f=null;b.nodeName===cb&&(f=G(b.nodeValue));c=c||!1;if("msie"===p.browser&&9>p.version&&e)return!1;if("msie"!==p.browser||9<=p.version)try{b.meta={ElementTag:d,ReadOnly:e}}catch(g){}if(f&&!this.is_html(f)&&3<=f.length){if(c&&"-1"===c)return!1;c=this._skim_id_hash(f,c);if(!c)return!1;a[c]=b}return f?!0:!1},_skim_id_hash:function(a){var c;if(!a)return"";c=G(a.replace(/\s+/g," ")).length;a=a.replace(/[:\s]*/g,
"");c=""+c+":"+a.substring(0,20);return c=zd(c)}}}();Fd=function(a,b,c,d){var e,f,g,m,h,k,R,p,t,n,o;e=j.createDocumentFragment();R=0;p=[];o=b.nodeValue;m=[];h=b.parentNode;d||(d="skimwords-potential");c||(c="-1");if(h){for(t=0,n=a.length;t<n;t++)g=a[t],k=j.createElement("span"),k.className=d,f=j.createTextNode(o.substring(R,g.start)),e.appendChild(f),k.innerHTML=g.text,e.appendChild(k),R={},R.node=k,R.match=g,l(R,"occurrence",g.target_occurrence),p.push(R),R=g.start+g.text.length,m.push(f),Ka.add_node(f,
c);a=j.createTextNode(o.substring(R));m.push(a);e.appendChild(a);Ka.add_node(a,c);h.replaceChild(e,b)}return[p,m]};wd=function(a,b,c){var d,e,f;if(oa)return!1;d=(a.data?a.data:a.childNodes[0].data).replace(b.repl_regex,b.replacement);f=j.createElement("span");b=j.createDocumentFragment();f.innerHTML=d;if("msie"===p.browser&&9>p.version&&(d=a.previousSibling,e=/^\s/,d&&d.nodeValue&&d.nodeValue.length&&e.test(d.nodeValue[d.nodeValue.length-1])&&(d.nodeValue+=" "),(d=a.nextSibling)&&d.nodeValue&&d.nodeValue.length&&
e.test(d.nodeValue[0])))d.nodeValue=" "+d.nodeValue;for(;f.firstChild;)f.firstChild.nodeName===cb?(d=b.appendChild(f.firstChild),Ka.add_node(d)):(d=b.appendChild(f.firstChild),null!==d&&!c&&(Fb(d,!0),ob(d,!0)));if(c=a.parentNode)return c.replaceChild(b,a)};Cd=function(a,b){10>parseInt(b)&&(b="0"+b);return"3"+a+"0"+b};vd=function(a,b){1E7<a&&6!==b&&(a-=1E7);return a};Ed=function(a,b,c){var d,e,f;f=b.phrase;d={};d.w=f.text();d.lp=f.url();if(c)d.t=Fc,e="unlinked";else{if(0===f.limit())return!1;f.dec_limit();
W+=1;d.ed=f.is_editor()?1:0;d.t=Cd("02",f.action_type(),f.group_id());e="skimwords";d.pid=0===f.group_id()?0:vd(f.id(),f.action_type())}Gd(d,e);wd(a,b,c);return!0};if("function"!==typeof Element.prototype.matches)Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||function(a){var b,a=(this.document||this.ownerDocument).querySelectorAll(a);for(b=0;a[b]&&a[b]!==this;)++b;return Boolean(a[b])};if("function"!==typeof Element.prototype.closest)Element.prototype.closest=
function(a){var b;for(b=this;b&&1===b.nodeType;){if(b.matches(a))return b;b=b.parentNode}return null};var Hd,Id,Jd,Kd,Ld,Md,Bc,Nd,ua,Fc;Fc="500005";Id=function(a){s(a,"click",K);ab||s(a,"contextmenu",K);Fb(a,!1);return ob(a)};Md=function(a){a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig.exec(a);return a.length&&""!==a[0]?!0:!1};Kd=function(a,b,c,d){var e,f;e=Pa(a);f="";E&&(f='target="'+E+'"');b=nb(b);e="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+
e+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";a='$1$2<a href="'+b+'" class="'+d+'" '+f+' data-skimwords-word="'+encodeURIComponent(nb(a))+('"  data-skim-creative="'+c+'" title="">$3$4</a>$5$6');b=e.replace(/\?:/g,"");return{search_regex:RegExp(e,"i"),repl_regex:RegExp(b,"i"),repl_text:a}};Hd=function(){var a,b,c,d,e;b=Y("skimlinks-unlinked");e=[];for(c=0,d=b.length;c<d;c++)a=b[c],e.push(Id(a));return e};Bc=function(a){var b,c,d,e;b={};if((c=a.merchant_domains)&&c.length){for(d=0,
e=c.length;d<e;d++)a=c[d],b[a]=!0;for(d=0,e=Gb.length;d<e;d++)c=Gb[d],a=c.match.domain,b.hasOwnProperty(a)&&Ed(c.node,c.match,!0)}Nc(10,function(){return Hd("skimlinks-unlinked")});try{return Ja("unlinked")}catch(f){return!0}};Jd=function(a,b){var c,d,e,f,g,h,j,l,k,n,t;if(!a||Dc(a,["span.skimlinks-unlinked"]))return[[],[]];t=a.data;e=[];h=[];for(k=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^\[\]\s]*\b|$/ig;d=k.exec(t);)if(c=d[0],"link.phrase"!==c)if(g=d.index,0<G(c).length&&
-1===c.indexOf("/.")&&-1===c.indexOf("..."))f=c,0!==c.indexOf("http")&&0!==c.indexOf("//")&&(f="msie"===p.browser&&6>=p.version?"http://"+c:"//"+c),d=Ca(f),l=Od({OriginalPhrase:""+c,Url:f,Title:"",ActionType:2,GroupId:0,Unlinked:!0}),(n=Kd(""+c,f,Fc,"skimlinks-unlinked"))&&h.push({start:g,text:""+nb(c),domain:d,repl_regex:n.repl_regex,replacement:n.repl_text,regex:n.search_regex,phrase:l,link:f}),e.push(d);else break;if(h.length){j=Fd(h,a,b,"skimlinks-unlinked");c=j[0];j=j[1];for(k=0,t=c.length;k<
t;k++)h=c[k],Gb.push(h)}j||(j=[]);return[e,j]};Nd=function(a){var b,c,d;if(na.length)for(c=0,d=na.length;c<d;c++)if(b=na[c],b===a)return!1;if(Z.length){for(c=0,d=Z.length;c<d;c++)if(b=Z[c],b===a)return!0;return!1}return!0};Ld=function(){var a,b,c,d,e,f,g;c=Ka.get_as_hash_node_dict();d={};for(b in c)if(a=c[b],a.parentNode&&!Wa(a)&&!la(a,"noskimwords")&&!la(a,"noskimlinks")&&!la(a,"noskimw")&&(!a.meta||!a.meta.ReadOnly)){a=Jd(a,b);g=a[0];for(e=0,f=g.length;e<f;e++)a=g[e],!d[a]&&Nd(a)&&(d[a]=!0,y.domains.push(a))}return y.domains.length?
qb(y.domains):Ja("unlinked")};ua=function(){var a;a=j.getElementsByTagName("body");a.length?(a=a[0].textContent||a[0].innerText)&&Md(a)?Ia?(Ka.traverse([],uc,[]),Ld()):getSkimwordsData("skimwordsSettingsCallback"):y.domains.length&&qb(y.domains):y.domains.length&&qb(y.domains)};h.skimlinksUnlinked=Bc;var Pd,Kb,Qd,Rd,n,La,Sd,Lb,Td,Ud,Vd,Wd,Xd,eb,Yd,F={}.hasOwnProperty;n={pag:"",pub:"",guid:"",uc:"",lnks:{}};La={};Rd=function(a,b){var c,d,e;e="GBP"===a.currency?"&pound;":"EUR"===a.currency?"&euro;":
"$";d=j.createElement("a");l(d,"href",a.url);l(d,"title",a.title);l(d,"target","_blank");Jc(d,"skimlinks-inline");l(d,"data-skim-creative",b);c=0;Ha&&(c=1);l(d,"data-skimlinks-editor",c);c=parseFloat(Math.round(100*a.price)/100).toFixed(2);d.innerHTML=""+a.merchant+" "+e+c;s(d,"mousedown",K);return d};Qd=function(a,b,c,d,e){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+e};Sd=function(a,b){var c,d,e,f,g,h,j;c=b.price;if(!c)return"0";d=0;e=1E8;g=0;for(h=0,j=a.length;h<j;h++)f=
a[h],f=parseFloat(f.price),f>d&&(d=f),parseFloat(f)<e&&(e=f),f===c&&g++;return 1<g?"4":c>=d?"3":c<=e?"1":"2"};Yd=function(a,b,c){var d,e,f,g,h;e=!1;for(d=g=0,h=a.length;g<h;d=++g)if(f=a[d],f.url===c){e=d;break}e&&(c=a[e],"beginning"===b?(a[e]=a[0],a[0]=c):"end"===b&&(a[e]=a[a.length-1],a[a.length-1]=c));return a};Xd=function(a){var b,c;if("1"===l(a,"ipc-added")){for(;")"!==(null!=(c=a.nextSibling)?c.textContent.substring(0,1):void 0);)(b=a.nextSibling)&&b.parentNode&&b.parentNode.removeChild(b);if(a&&
a.parentNode&&a.nextSibling)return a.parentNode.removeChild(a.nextSibling)}};Pd=function(a,b,c,d,e,f,g){var m,k,n,p,o,t,w,q,r,s,v,u,x,y;Xd(b);n=!0;o=b;p=!1;c=Yd(c,rc,d);e.hasOwnProperty(d)?(t=e[d],f[t].cnt++):(g[d]={},t={},t.lpid=d,t.cnt=1,t.url=b.href.replace(ya,""),t.prd=[],t.ed=Ha?1:0,f.push(t),t=f.length-1,e[d]=t);"cross"===Ea?l(b,"style","text-decoration: line-through !important;"):"text"===Ea?null!=b.parentNode&&(e=null!=(q=Yc(b.parentNode,"color"))?q:"#000",l(b,"style","color: "+e+" !important; text-decoration: none !important;")):
"blink"===Ea&&l(b,"style","text-decoration: blink !important;");e=c.length;q=0;if(h.skimlinks_editor)x=b.parentNode,u=j.createElement("span"),v=j.createElement("span"),m=b.cloneNode(!0),u.appendChild(m),u.appendChild(v),u.style.display="inline !important",u.classList.add("sl-select-wrapper"),v.classList.add("sl-select-products"),m.classList.add("sl-select-link");for(m=0,y=c.length;m<y;m++){w=c[m];p=!0;s=w.currency+w.price+w.url+w.title+w.merchant;q+=1;k=Sd(c,w);k=Qd(Ea,k,e,a,q);if(!g[d].hasOwnProperty(s))r=
{},r.cur=w.currency,r.mn=w.merchant,r.mid=w.merchant_id,r.pr=w.price,r.ti=w.title,r.pu=w.url.replace(ya,""),r.cr=k,f[t].prd.push(r),g[d][s]=!0;w=Rd(w,k);n?(s=j.createTextNode(" ("),n=!1):s=j.createTextNode(" | ");h.skimlinks_editor?(v.appendChild(s),v.appendChild(w)):(o.parentNode.insertBefore(s,o.nextSibling),s.parentNode.insertBefore(w,s.nextSibling));o=w}h.skimlinks_editor&&x.replaceChild(u,b);n||(a=j.createTextNode(") "),o.parentNode.insertBefore(a,o.nextSibling));l(b,"ipc-added",1);return p};
Ud=function(a,b,c){var d,e;for(e in b)if(F.call(b,e)&&(d=b[e],e===a&&(0===d.length||ia(c,d))))return!0;return!1};Kb=function(a){var b,c,d,e,f,g,h,j,k,n,o;if(!a)return!1;d={};e=[];g={};c=[];j=!1;for(k in a)if(F.call(a,k)&&La.hasOwnProperty(k)&&(h=a[k],h.length)){f=La[k];for(n=0,o=f.length;n<o;n++)b=f[n],k=G(b.href),l(b,"rel"),Pd(1,b,h,k,d,e,g)&&(j=!0),c.push({url:k,occurrence:l(b,"data-occurrence"),products:h})}j&&"undefined"!==typeof Mb&&null!==Mb&&Mb(e);"undefined"!==typeof setSelectLinks&&null!==
setSelectLinks&&setSelectLinks(c);return!0};Td=function(){var a;a="//ipc.skimresources.com/api/select_whitelist.php?callback=selectWhitelistCallback&data="+o(r({pubcode:C,page:z.href}));return ha(a,!1,{},Lb,[])};Vd=function(a){var b,c,d,e,f,g;e="//ipc.skimresources.com/api/select.php?callback=selectCallback&urls=";b="msie"===p.browser?2E3:8E3;c=[];for(f=0,g=a.length;f<g;f++)d=a[f],c.push(d),d=o(r(c)).length,d+e.length>b&&(c=c.slice(0,-1));if(c.length)return e+=o(r(c)),ha(e,!1,{},Kb,!1)};Wd=function(a){var b;
b={urls:r(a),debug:1};b=wa(b);(X||!Xa("//ipc.skimresources.com/api/select.php",b,Kb))&&Vd(a);return!0};Lb=function(a){var b,c,d,e,f,g,h,j,k,n,o,p,q,r,s;if(!1!==a&&0===a.length)return!1;o=[];g={};h=Y();k=0;for(p=0,r=h.length;p<r;p++)if(b=h[p],e=L(b.hostname),n=G(b.href),j=l(b,"rel"),d=b.childNodes,!yb.length||ia(e,yb)){if(d&&d.length){f=!1;for(q=0,s=d.length;q<s;q++)c=d[q],c.nodeName&&"IMG"===c.nodeName.toUpperCase()&&(f=!0);if(f)continue}if(ja(n,e)&&ka(j)&&Da(e)&&(g.hasOwnProperty(n)||(g[n]=0),g[n]++,
l(b,"data-occurrence",g[n]),l(b,"data-select-id",k),k++,!a||Ud(n,a,g[n])))if(c=l(b,"class"),!c||!(-1!==c.indexOf("skimlinks-inline")||-1!==c.indexOf("skimwords-link")))if("undefined"===typeof La[n]&&(La[n]=[]),La[n].push(b),ia(n,o)||o.push(n),100<=o.length)break}return 0===o.length?!1:Wd(o)};eb=function(){return Ha?Td():Lb(!1)};h.selectCallback=Kb;h.selectWhitelistCallback=Lb;h.skimlinksApplySelect=eb;var Od;Od=function(a){var b,c,d,e;d=b=null;c=5;a.Limit&&(c=a.Limit);e=function(){return a.Priority||
0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return c-1},limit:function(){return c},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},is_editor:function(){return null!=a.ValidOn&&""!==a.ValidOn?!0:!1},is_blacklisted:function(){return null!=a.IsBlacklisted?a.IsBlacklisted:!1},group_priority:function(){return b?b.group_priority():e()},
id:function(){return d?d:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){return a.Unlinked?a.Title="":a.Title=b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return d=a}}};var Gd,gb,Zd,k,$,Q,Gc,$d,ae,be,ud,Ja,Mb,ta,Nb,Ma,F={}.hasOwnProperty;Q="//t.skimresources.com/api/";k={pag:"",phr:[],unl:[],pub:"",
slc:0,swc:0,ulc:0,jsl:0,jsf:"",guid:"",uuid:"",sessid:"",uc:"",t:1,slmcid:!1};$={skimlinks:!0,skimwords:!0,unlinked:!0};Ma=0;Gc=!1;Gd=function(a,b){var c,d,e,f;c=!0;if("skimwords"===b){for(e=0,f=fa.length;e<f;e++)if(d=fa[e],c=d.pid?d.pid===a.pid:d.w===a.w)return c;fa.push(a)}else if("unlinked"===b){for(e=0,f=ga.length;e<f;e++)d=ga[e],d.w===a.w&&(c=!1);c&&ga.push(a);Ma++}return c};ae=function(){var a,b,c,d,e,f;a=8E3;"msie"===p.browser&&(a=2E3);d={};d.guid=v;d.uuid=H;d.sessid=D;d.pub=C;d.pag=z.href;
d.tz=A;d.slmcid=V;d.dl={};d.typ="l";d.hae=J?1:0;c=""+Q+"link?data=";f=0;for(e in q)F.call(q,e)&&(b=q[e],f++,d.dl[e]=b,b=c+o(r(d)),b.length>a&&(f--,delete d.dl[e]));f&&(c+=o(r(d)),ha(c,!1,{async:!0}));return!0};ta=function(){var a;if(db)return!1;a={};a.guid=v;a.uuid=H;a.sessid=D;a.pub=C;a.pag=z.href;a.dl=q;a.tz=A;a.slmcid=V;a.typ="l";a.hae=J?1:0;a={data:r(a)};u&&(a.dnt=u);M&&(a.fdnt=1);a=wa(a);if(X||!Xa(""+Q+"link",a,Nb))return ae()};ud=function(a){var b,c,d;b=g("pageTracker");d=g("urchinTracker");
c="/"+bb+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;g("_gaq")?(b=g("_gaq"),b.push(["_trackEvent",bb,"click",a])):g("ga")&&g("ga")("send","event","click",bb,a);return!1};$d=function(a){var b,c,d,e,f;n.tz=A;n.guid=v;n.uuid=H;n.sessid=D;n.pref=P;n.lnks=[];n.typ="s";b=8E3;"msie"===p.browser&&(b=2E3);c=""+Q+"ipc?data=";for(e=0,f=a.length;e<f;e++)d=a[e],n.lnks.push(d),d=c+o(r(n)),d.length>b&&(n.lnks=n.lnks.slice(0,-1));n.lnks.length&&(c+=o(r(n)),ha(c,!1,{async:!0}));
return!0};Mb=function(a){var b;if(db)return!1;n.tz=A;n.guid=v;n.uuid=H;n.sessid=D;n.pref=P;n.lnks=a;n.typ="s";b={data:r(n)};b=wa(b);(X||!Xa(""+Q+"ipc",b,Nb))&&$d(a);return!0};Nb=function(){return!0};Ja=function(a){var b,c;if(db||Gc)return!1;$[a]=!1;a=!0;for(b in $)if(F.call($,b)&&(c=$[b],!0===c)){a=!1;break}if(a)return Gc=!0,Zd()};gb=function(a){var b,c,d,e,f;if(a instanceof Array){c={};for(b=e=0,f=a.length;e<f;b=++e)d=a[b],c[""+b]=d;return c}return a};be=function(){var a,b,c,d,e;a=(new Date).getTime()-
Yb;b=8E3;"msie"===p.browser&&(b=2E3);k.tz=A;k.slc=J;k.swc="undefined"!==typeof W&&null!==W?W:0;k.ulc=null!=Ma?Ma:0;k.jsl=a;k.guid=v;k.slmcid=V;k.uuid=H;k.sessid=D;k.pref=P;k.phr=[];k.unl=[];oa&&(k.xrf=1);a=""+Q+"track.php?";u&&(a=a+"dnt="+u+"&");M&&(a+="fdnt=1&");X&&(a+="abp=1&");a+="data=";for(c=d=0,e=fa.length;d<e;c=++d)c=fa[c],k.phr.push(c),c=a+o(r(k).replace(ya,"")),c.length>b&&(k.phr=k.phr.slice(0,-1));for(c=d=0,e=ga.length;d<e;c=++d)c=ga[c],k.unl.push(c),c=a+o(r(k).replace(ya,"")),c.length>
b&&(k.unl=k.unl.slice(0,-1));k.phr=gb(k.phr);k.unl=gb(k.unl);b=a+o(r(k).replace(ya,""));ha(b,!1,{async:!0});return tb(1)};Zd=function(){var a;a=(new Date).getTime()-Yb;k.tz=A;k.slc=J;k.swc="undefined"!==typeof W&&null!==W?W:0;k.ulc=null!=Ma?Ma:0;k.jsl=a;k.guid=v;k.slmcid=V;k.uuid=H;k.sessid=D;k.pref=P;a=k;a.phr=gb(fa);a.unl=gb(ga);a={data:r(a)};u&&(a.dnt=u);M&&(a.fdnt=1);a=wa(a);if(X||!Xa(""+Q+"track.php",a,Nb))return be(),!0;null!=h.skimlinks_runner&&(h.skimlinks_runner.tracking=1);tb(1);return!0};
var ce=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(f.complete&&g.complete&&(e=!0),e&&"0"!=f.width&&"0"==g.width&&(d=!0))}var d=!1,e=!1,f=null,g=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(h){}b=11*Math.random();f=new Image;f.onload=c;f.src=a.replace(/\*/,1).replace(/\*/,b);g=new Image;g.onload=
c;g.src=a.replace(/\*/,2).replace(/\*/,b)})()}("//p.skimresources.com/px.gif?ch=*&rn=*");kc()})(this);
